<?php
/**
 * @category    Grafikentwicklung
 * @package     Tracking
 * @author      Grafik, Entwicklung & IT Service <info@pierrearlt.com>
 * @date        21.11.2016
 * @license     https://github.com/parlt/Grafikentwicklung_Tracking/blob/master/LICENSE The MIT License (MIT)
 */

/**
 * @var Grafikentwicklung_Tracking_Block_TagManager_Body $this ;
 */
?>
<?php
if ($this->getTrackingHelper()->canUseTagManager()) { ?>
    <!-- Tag Manager Tracking (noscript) Begin -->
    <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PLKBPS"
                height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <!-- Tag Manager Tracking (noscript) End -->
<?php } ?>