<?php
/**
 * @category    Grafikentwicklung
 * @package     Tracking
 * @author      Grafik, Entwicklung & IT Service <info@pierrearlt.com>
 * @date        21.11.2016
 * @license     https://github.com/parlt/Grafikentwicklung_Tracking/blob/master/LICENSE The MIT License (MIT)
 */

/**
 * Class Grafikentwicklung_Tracking_Model_Resource_Abstract
 */
class Grafikentwicklung_Tracking_Model_Resource_Abstract extends Mage_Core_Model_Resource_Db_Abstract
{

    protected function _construct(){}


    /**
     * @param Mage_Core_Model_Abstract|Grafikentwicklung_Tracking_Model_Resource_Salestracking|Grafikentwicklung_Tracking_Model_Salestracking  $object
     * @return Mage_Core_Model_Resource_Db_Abstract|Grafikentwicklung_Tracking_Model_Resource_Salestracking|Grafikentwicklung_Tracking_Model_Salestracking
     */
    protected function _beforeSave(Mage_Core_Model_Abstract $object)
    {
        /** @var string $dateTime */
        $dateTime = date('m/d/Y h:i:s', time());

        if ($object->getId()) {
            $object->setData('update_time', $dateTime);
        } else {
            $object->setData('update_time', $dateTime);
            $object->setData('created_time', $dateTime);
        }

        return parent::_beforeSave($object); // TODO: Change the autogenerated stub
    }
}