<?php
/**
 * @category    Grafikentwicklung
 * @package     Tracking
 * @author      Grafik, Entwicklung & IT Service <info@pierrearlt.com>
 * @date        21.11.2016
 * @license     https://github.com/parlt/Grafikentwicklung_Tracking/blob/master/LICENSE The MIT License (MIT)
 */

/**
 * @var Grafikentwicklung_Tracking_Block_Shopzilla_Body $this
 */
?>
<?php if ($this->getHelper()->canUseShopZillaTracking()) {
    $tackingData = $this->getShopZillaSalesTrackingData(); ?>
    <!-- Shopzilla Tracking Begin-->
    <script language="javascript">
        var mid = '<?php echo $this->getHelper()->getShopZillaMerchantId();?>';
        var cust_type = '<?php echo $tackingData['cust_type']; ?>';
        var order_value = '<?php echo $tackingData['order_value'];?>';
        var order_id = '<?php echo $tackingData['order_id'];?>';
        var units_ordered = '<?php echo $tackingData['units_ordered'];?>';
    </script>
    <script language="javascript" src="https://images.bizrate.com/api/roi_tracker.min.js?v=1"></script>
    <!-- Shopzilla Tracking End -->
<?php } ?>